### ISSUE TITLE
netty breaks nim CI

### ISSUE THREAD

**Issue by timotheecour** [treeform/netty#22]
https://github.com/nim-lang/Nim/runs/3056575693

```
PASS: [14/37] msgpack4nim c                                                ( 4.20 sec)
  FAIL: [15/37] netty c                                                      (35.52 sec)
  Test "netty" in category "nimble-packages"
  Failure: reBuildFailed
  nimble test
    Verifying dependencies for netty@0.2.0
        Info: Dependency on flatty@>= 0.1.0 already satisfied
    Verifying dependencies for flatty@0.2.2
    Compiling /Users/runner/work/Nim/Nim/pkgstemp/netty/tests/test (from package netty) using c backend
  Received packet of invalid size 127.0.0.1:3016
  diff --git a/tests/test-output.txt b/tests/test-output.txt
  index bf9159a..2128f75 100644
  --- a/tests/test-output.txt
  +++ b/tests/test-output.txt
  @@ -39,7 +39,6 @@ many clients stress test
   100 clients
   
   punch through test
  -MESSAGE hi
   testing maxUdpPacket and maxInFlight
   sent6006
   testing retry
  
  Output does not match
  Error: execution of an external program failed: '/Users/runner/work/Nim/Nim/pkgstemp/netty/tests/test '
         Tip: 3 messages have been suppressed, use --verbose to show them.
       Error: Execution failed with exit code 256
          ... Command: /Users/runner/work/Nim/Nim/bin/nim c --noNimblePath -d:NimblePkgVersion=0.2.0 --path:/Users/runner/.nimble/pkgs/flatty-0.2.2 --hints:off -r --path:. /Users/runner/work/Nim/Nim/pkgstemp/netty/tests/test
  
  PASS: [16/37] nimcrypto c                                                  (64.73 sec)
```

**Comment by treeform** [comment]
We have not changed netty in a long time. The break is probably related to Nim's change in networking or some thing like that.

**Comment by timotheecour** [comment]
> The break is probably related to Nim's change in networking or some thing like that.

but it doesn't work either in earlier versions of nim, so the bug is likely elsewhere, possibly in one of netty's (transitive) dependencies

```
git clone https://github.com/treeform/netty
cd netty
NIMBLE_DIR=$HOME/.nimble_fake73 XDG_CONFIG_HOME= nimble develop # install dependencies
NIMBLE_DIR=$HOME/.nimble_fake73 XDG_CONFIG_HOME= nimble test
```
errors with:
```
Received packet of invalid size 127.0.0.1:3016
diff --git a/tests/test-output.txt b/tests/test-output.txt
index bf9159a..0fff2ae 100644
--- a/tests/test-output.txt
+++ b/tests/test-output.txt
@@ -1,6 +1,5 @@
 Testing netty
 simple test
-MESSAGE hi
 main test
 REACTOR: server (127.0.0.1:3001)
 REACTOR: client (127.0.0.1:3002)
...
```

likewise if i do directly:
`NIMBLE_DIR=$HOME/.nimble_fake73 XDG_CONFIG_HOME= nim c -r tests/test.nim`

depending on the runs i either get:
* `tests/test.nim(89, 10) `len(client.deadConnections) == 1`  [AssertionDefect]`
* or the above error
* or in rare cases, it succeeds

likewise with older nim versions, eg 1.4.0, eg via:

`NIMBLE_DIR=$HOME/.nimble_fake73 XDG_CONFIG_HOME= $nim_140_X c -r tests/test.nim`

likewise with 1.2.0

so the test was flaky at best, either way, there is a bug that seems unrelated to recent changes in nim

**Comment by guzba** [comment]
`nimble test` repeatedly passes for me without issue on Windows. Treeform has updated the one dep netty has to see if that still works. He's not able to see tests ever fail either afaik, he can confirm or deny that here.

**Comment by timotheecour** [comment]
this only affects OSX, judging from all the CI failures I've seen

**Comment by guzba** [comment]
Confirmed issue on Mac only, caused by very different recvFrom behavior.

**Comment by timotheecour** [comment]
can you provide more details, ideally in form of a minimized bug that doesn't involve netty if that's a bug that should be fixed in nim stdlib?

**Comment by guzba** [comment]
Treeform is working on this directly, I'm just chatting with him so I don't know all the details. The difference is not in Nim from my understanding, it's related to how non-blocking socket + a read when nothing is ready to be read works on Mac vs others.

Netty is meant for games, so each frame you check if data is ready on the non-blocking socket. On Windows and Linux this is fine. On Mac it seems to be less happy about that. In the tests case, it is tied in to how long it takes for write to localhost to be ready to be read. Seems pretty much instant on Windows and Linux but Mac seems to need a sleep() to make things work. 2 parts of oddness.

**Comment by timotheecour** [comment]
> Mac seems to need a sleep() to make things work

I'm lacking context but usually, using std/selectors (which wraps kqueue or poll etc) is the way to go, avoiding un-necessary sleep and avoiding blocking.

**Comment by guzba** [comment]
Yes, but there's specifically no point for a game, which is explicitly what netty is for. Each frame, you just check and move on. This happens more than enough to process everything but not so often as to be crazy. No blocking, very simple. No need to wait on a selector and wire that mess up, nor any threads or blocking at all. UDP is very simple and there's no need to make a game work like a web server.

(The need to sleep is explicitly just to make Mac pass tests and will be behind a `when`. In reality it does not matter if a packet arrives on frame 1024 or 1025.)

**Comment by treeform** [comment]
@timotheecour I have fixed the issues on macOS. All tests now pass on macOs, linux and windows.

The issue is that for some reason writing to localhost on mac is not instant like it is on linux and windows. @guzba is right games deal with very few connections - usually 1. There is no need to block or use selectors its just more work. Just read from the UDP socket if it has anything and move on. The sleep is only needed for tests, no need in actual operation.

**Comment by timotheecour** [comment]
thanks for fixing this, I'll close it now seems like it seems like tests pass in nim CI; any idea why it started failing recently despite no recent change in netty and despite being unrelated to recent nim changes?

**Comment by treeform** [comment]
I don't know why it started to happen. Maybe Mac CI upgraded the OS. And now all newer Macs have a localhost UDP delay?
