### ISSUE TITLE
Client crash on double disconnect

### ISSUE THREAD

**Issue by enthus1ast** [treeform/netty#25]
When disconnect is called twice the client crashes with:
`Error: unhandled exception: value out of range: -1 notin 0 .. 9223372036854775807 [RangeDefect]`

client.nim
```nim
import netty
var client = newReactor()
var c2s = client.connect("127.0.0.1", 1999)
client.send(c2s, "hi")
client.disconnect(c2s)
client.disconnect(c2s)
```

server.nim
```nim
import netty

var server = newReactor("127.0.0.1", 1999)
echo "Listenting for UDP on 127.0.0.1:1999"
while true:
  server.tick()
  for msg in server.messages:
    echo "GOT MESSAGE: ", msg.data
    server.send(msg.conn, "you said:" & msg.data)
```

**Comment by treeform** [comment]
Thank you for the bug report! 

I have a fixed it: https://github.com/treeform/netty/commit/8df45fd5e7d722e4256d8814a0aa5916f26471d8

Please update to netty v`0.2.1` to get the fix.

Thanks!

**Comment by treeform** [comment]
If you still have issues, feel free to re-open.
