### ISSUE TITLE
High CPU load for server/client tests

### ISSUE THREAD

**Issue by ba0f3** [treeform/netty#3]
I got 100% CPU per server/client process. here is what strace gives me:
```
strace: Process 14805 detached
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
100.00    1.583756           0   1718806   1718806 recvfrom
------ ----------- ----------- --------- --------- ----------------
100.00    1.583756               1718806   1718806 total
```
Probably this line cause the load: https://github.com/treeform/netpipe/blob/634fbee0d1cfea3e58d2e0dc73015fdca4eb1718/src/netpipe.nim#L317

**Comment by treeform** [comment]
You are right the examples need to have a sleep() in their tight loops.

**Comment by treeform** [comment]
Fixed!
