### ISSUE TITLE
Disconnect Packet

### ISSUE THREAD

**Issue by seruum** [treeform/netty#4]
Is there a timeline when the disconnect packet function will be ready?
I could try to implement it with some pointers to get into the right direction. It didn't seem obvious to me when reviewing the code.

**Comment by treeform** [comment]
Yeah I need to add this.

**Comment by treeform** [comment]
Sorry this was implemented long time ago. I just forgot to close this issue.

https://github.com/treeform/netty/commit/b113054cd91498c5da6a5b9d1accef1ed6f2130f

Sorry!
