### ISSUE TITLE
Getting disconnected frequently.

### ISSUE THREAD

**Issue by mikebelanger** [treeform/netty#5]
Cool project!  I tried out the chatserver example on the main page.  I can send 1 or 2 messages, then I get
```[dead] 127.0.0.1:58372```.
In one of the clients.  Doesn't look like it recovers either.  

I'm on OS X 10.13.6, using nim 1.0.2.

I feel like I'm just missing something here.  Maybe its an OS-level config issue?  Thanks.

**Comment by treeform** [comment]
Do you call reactor.tick() in your tight loop? Both server and client need this.

**Comment by mikebelanger** [comment]
Sorry for taking so long to reply.  I was just running the chat example off the main page.  that said, I just tried again with nim compiler v 1.1.1.  I haven't gotten disconnected.  So whatever happened before was likely an issue with either my system, or potentially an older version of nim.  definitely good this is closed.
